

[params]
rss = true
description = "I'm a Lead Software Engineer at an early-stage startup, focused on building scalable infrastructure with Kubernetes, Go, and GraphQL. I have a strong background in system design, GPU programming, and computer graphics, and have led multiple startups from 0 to 1 through MVP development. This site is a collection of my technical write-ups, startup lessons, and occasional experiments in software engineering."
metaDescription = "Technical blog by Oleg Pustovit, covering scalable infrastructure, MVPs, Kubernetes, Go, GraphQL, and startup engineering lessons."
metaKeywords = "Software Engineering, Kubernetes, Go, GraphQL, Startups, MVP, System Design, Tech Blog, Oleg Pustovit"
colortheme = "classic"
worksFor = "Early-stage startup"
jobTitle = "Lead Software Engineer"
author = "Oleg Pustovit"
title = "Oleg Pustovit – Technical Blog on Scalable Systems, Startups & Engineering"

[params.hero]
cta = "Need technical firepower? Let's talk"
sidebarText = "Technical leadership for **startups**, **scale-ups**, and **founders** who are tired of duct tape disguised as code. From **AI prototypes** to **production-grade** systems, it's handled."


[[params.social]]
name = "github"
link = "https://github.com/nexo-tech"

[[params.social]]
name = "email"
link = "oleg@nexo.sh"

[[params.social]]
name = "x-twitter"
link = "https://x.com/nexo_v1"

[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/in/nexo-tech/"


[params.introduction]
title = "Oleg Pustovit"
description = "I'm a Lead Software Engineer at an early-stage startup, focused on building scalable infrastructure with Kubernetes, Go, and GraphQL. I have a strong background in system design, GPU programming, and computer graphics, and have led multiple startups from 0 to 1 through MVP development. This site is a collection of my technical write-ups, startup lessons, and occasional experiments in software engineering."

[[params.services]]
title = "MVP Development"
description = "End-to-end product buildout with scalable architecture."

[[params.services]]
title = "Fractional CTO"
description = "Architecture, team building, and technical roadmap planning."

[[params.services]]
title = "Code Reviews / Audits"
description = "Deep technical analysis to prevent those 3 AM production issues."

[[params.services]]
title = "Hiring / Team Building"
description = "Building high-performance engineering teams that actually ship."

[params.aboutMe]
text = "I transform complex technical challenges into elegant, scalable solutions. With a background in both design and development, I bridge the gap between vision and execution."

[[params.aboutMe.values]]
value = "Clean, maintainable code over quick hacks"

[[params.aboutMe.values]]
value = "Clear communication above all"

[[params.aboutMe.values]]
value = "Users first, tech stack second"

[[params.aboutMe.values]]
value = "Continuous learning and adaptation"

[[params.aboutMe.timeline]]
year = "2025"
description = "Tech Leadership & Advisory"
subtext = "Guiding early-stage startups as a technical lead and consultant."

[[params.aboutMe.timeline]]
year = "2023"
description = "From Engineer to Lead"
subtext = "Led development across multiple SaaS platforms, managing teams and architecting full-stack systems."

[[params.aboutMe.timeline]]
year = "2021"
description = "Rapid Growth in Engineering"
subtext = "Joined as intern, promoted to lead within 18 months. Delivered MVPs in Node.js, React, and AWS."

[[params.aboutMe.timeline]]
year = "2018"
description = "Creative Foundations"
subtext = "Explored design and freelance work before fully transitioning into software engineering."

[params.writingsGrid]
columns = 3     # Number of columns in the grid (can be 3, 4, 5, etc.)
postsToShow = 6 # Number of posts to display in the grid

[params.forms.newsletter]
action = "https://app.kit.com/forms/7961988/subscriptions"
formId = "7961988"
uid = "842da55da6"
format = "inline"
version = "5"
