baseURL = 'https://nexo.sh/'
languageCode = 'en-us'
title = 'nexo blog'
copyright = "Oleg Pustovit"

[markup]
[markup.highlight]
noClasses = false
style = 'catppuccin-latte'
lineNos = true


[build]
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = 'css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'
[module]
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
disableWatch = true
source = 'hugo_stats.json'
target = 'assets/notwatching/hugo_stats.json'


[params]
rss = true
description = "I'm a Lead Software Engineer at an early-stage startup, focused on building scalable infrastructure with Kubernetes, Go, and GraphQL. I have a strong background in system design, GPU programming, and computer graphics, and have led multiple startups from 0 to 1 through MVP development. This site is a collection of my technical write-ups, startup lessons, and occasional experiments in software engineering."
metaDescription = "Technical blog by Oleg Pustovit, covering scalable infrastructure, MVPs, Kubernetes, Go, GraphQL, and startup engineering lessons."
metaKeywords = "Software Engineering, Kubernetes, Go, GraphQL, Startups, MVP, System Design, Tech Blog, Oleg Pustovit"
colortheme = "classic"
worksFor = "Early-stage startup"
jobTitle = "Lead Software Engineer"
author = "Oleg Pustovit"
title = "Oleg Pustovit – Technical Blog on Scalable Systems, Startups & Engineering"

[params.hero]
cta = "Need technical firepower? Let's talk"
sidebarText = "Technical leadership for **startups**, **scale-ups**, and **founders** who are tired of duct tape disguised as code. From **AI prototypes** to **production-grade** systems, it's handled."


[[params.social]]
name = "github"
link = "https://github.com/nexo-tech"

[[params.social]]
name = "email"
link = "oleg@nexo.sh"

[[params.social]]
name = "x-twitter"
link = "https://x.com/nexo_v1"

[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/in/nexo-tech/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Privacy"
url = "/privacy-policy"
weight = 3

[params.introduction]
title = "Oleg Pustovit"
description = "I'm a Lead Software Engineer at an early-stage startup, focused on building scalable infrastructure with Kubernetes, Go, and GraphQL. I have a strong background in system design, GPU programming, and computer graphics, and have led multiple startups from 0 to 1 through MVP development. This site is a collection of my technical write-ups, startup lessons, and occasional experiments in software engineering."

[[params.services]]
title = "MVP Development"
description = "End-to-end product buildout with scalable architecture."

[[params.services]]
title = "Fractional CTO"
description = "Architecture, team building, and technical roadmap planning."

[[params.services]]
title = "Code Reviews / Audits"
description = "Deep technical analysis to prevent those 3 AM production issues."

[[params.services]]
title = "Hiring / Team Building"
description = "Building high-performance engineering teams that actually ship."

[params.aboutMe]
text = "I transform complex technical challenges into elegant, scalable solutions. With a background in both design and development, I bridge the gap between vision and execution."

[[params.aboutMe.values]]
value = "Clean, maintainable code over quick hacks"

[[params.aboutMe.values]]
value = "Clear communication above all"

[[params.aboutMe.values]]
value = "Users first, tech stack second"

[[params.aboutMe.values]]
value = "Continuous learning and adaptation"

[[params.aboutMe.timeline]]
year = "2022"
description = "Independent Consulting"
subtext = "Helping startups build and scale their tech."

[[params.aboutMe.timeline]]
year = "2020"
description = "First Startup Success"
subtext = "Led development of a SaaS platform from 0 to 10k users."

[[params.aboutMe.timeline]]
year = "2018"
description = "Building a SaaS platform"
subtext = "Discovered the joy of building things people actually use."


[params.skills]
primary = [
  "React",
  "Node.js",
  "TypeScript",
  "AWS",
  "Python",
  "Go",
  "Kubernetes",
  "Docker",
  "PostgreSQL",
  "Redis",
  "GraphQL",
  "Next.js",
  "Rust",
  "Java",
  "Swift",
  "Kotlin",
]
secondary = [
  "MongoDB",
  "MySQL",
  "Cassandra",
  "Elasticsearch",
  "RabbitMQ",
  "Kafka",
  "WebSocket",
  "gRPC",
  "TensorFlow",
  "PyTorch",
  "OpenCV",
  "Pandas",
  "NumPy",
  "Scikit-learn",
  "Django",
  "Flask",
  "FastAPI",
  "Spring Boot",
  "Gin",
  "Echo",
  "Actix",
  "Rocket",
  "Vue.js",
  "Angular",
  "Svelte",
  "Solid",
  "Qwik",
  "Astro",
  "Remix",
  "Nuxt",
  "Tailwind CSS",
  "Styled Components",
  "Sass",
  "Less",
  "PostCSS",
  "Bootstrap",
  "Material UI",
  "Chakra UI",
  "Ant Design",
  "Framer Motion",
  "Three.js",
  "D3.js",
  "Jest",
  "Cypress",
  "Playwright",
  "Vitest",
  "Mocha",
  "Chai",
  "Sinon",
  "JUnit",
  "Terraform",
  "Ansible",
  "Puppet",
  "Chef",
  "Prometheus",
  "Grafana",
  "ELK Stack",
  "GitHub Actions",
  "GitLab CI",
  "Jenkins",
  "CircleCI",
  "ArgoCD",
  "Flux",
  "Helm",
  "Istio",
  "Linkerd",
  "Envoy",
  "Nginx",
  "Apache",
  "Caddy",
  "Traefik",
  "Prisma",
  "TypeORM",
  "Sequelize",
  "Mongoose",
  "SQLAlchemy",
  "Hibernate",
  "Storybook",
  "Sentry",
  "Datadog",
  "New Relic",
  "LogRocket",
  "Amplitude",
  "Stripe",
  "PayPal",
  "Square",
  "Plaid",
  "Twilio",
  "SendGrid",
  "Mailchimp",
  "Firebase",
  "Supabase",
  "Appwrite",
  "Hasura",
  "Sanity",
  "Contentful",
  "WebRTC",
  "WebGL",
  "WebAssembly",
  "WebAuthn",
  "WebSocket",
  "WebTransport",
  "PWA",
  "Service Workers",
  "IndexedDB",
  "Web Storage",
  "Web Crypto",
  "Web Components",
  "Shadow DOM",
  "Custom Elements",
  "HTML Templates",
  "CSS Grid",
  "CSS Flexbox",
  "CSS Variables",
  "CSS Animations",
  "CSS Transitions",
  "Webpack",
  "Vite",
  "Rollup",
  "Parcel",
  "ESBuild",
  "SWC",
  "Babel",
  "ESLint",
  "Prettier",
  "Stylelint",
  "Husky",
  "lint-staged",
  "Commitlint",
  "Jira",
  "Trello",
  "Asana",
  "Monday",
  "ClickUp",
  "Notion",
  "Confluence",
  "Figma",
  "Sketch",
  "Adobe XD",
  "InVision",
  "Zeplin",
  "Abstract",
  "VS Code",
  "IntelliJ",
  "WebStorm",
  "Sublime Text",
  "Vim",
  "Neovim",
  "Git",
  "Mercurial",
  "SVN",
  "Perforce",
  "Plastic SCM",
  "Fossil",
  "Linux",
  "macOS",
  "Windows",
  "BSD",
  "Solaris",
  "AIX",
  "HP-UX",
  "ARM",
  "x86",
  "RISC-V",
  "MIPS",
  "PowerPC",
  "SPARC",
  "Itanium",
  "TCP/IP",
  "HTTP/2",
  "HTTP/3",
  "QUIC",
  "gRPC",
  "GraphQL",
  "REST",
  "OAuth",
  "OpenID",
  "SAML",
  "JWT",
  "OIDC",
  "LDAP",
  "Kerberos",
  "AES",
  "RSA",
  "ECC",
  "SHA",
  "HMAC",
  "PBKDF2",
  "Argon2",
  "TLS",
  "SSL",
  "IPSec",
  "WireGuard",
  "OpenVPN",
  "SSH",
  "SFTP",
  "DNS",
  "DHCP",
  "NTP",
  "SNMP",
  "SMTP",
  "IMAP",
  "POP3",
  "CDN",
  "Edge Computing",
  "Serverless",
  "Microservices",
  "Monolith",
  "Event Sourcing",
  "CQRS",
  "DDD",
  "TDD",
  "BDD",
  "Clean Architecture",
  "SOLID",
  "DRY",
  "KISS",
  "YAGNI",
  "GRASP",
  "Design Patterns",
  "Agile",
  "Scrum",
  "Kanban",
  "XP",
  "Lean",
  "SAFe",
  "DevOps",
  "CI/CD",
  "GitOps",
  "Infrastructure as Code",
  "Configuration as Code",
  "Observability",
  "Telemetry",
  "Tracing",
  "Logging",
  "Monitoring",
  "Performance",
  "Security",
  "Accessibility",
  "SEO",
  "Analytics",
  "Machine Learning",
  "Deep Learning",
  "Computer Vision",
  "NLP",
  "Blockchain",
  "Cryptography",
  "Quantum Computing",
  "IoT",
  "AR",
  "VR",
  "MR",
  "XR",
  "WebXR",
  "Unity",
  "Unreal Engine",
  "Game Development",
  "Mobile Development",
  "Desktop Development",
  "Cloud Computing",
  "Edge Computing",
  "Fog Computing",
  "Grid Computing",
  "Distributed Systems",
  "High Availability",
  "Fault Tolerance",
  "Resilience",
  "Scalability",
  "Performance",
  "Security",
  "Privacy",
  "Compliance",
  "GDPR",
  "CCPA",
  "HIPAA",
  "SOC 2",
  "ISO 27001",
  "PCI DSS",
]
tertiary = [
  "Alpine.js",
  "Stimulus",
  "Hotwire",
  "Turbo",
  "Strada",
  "Cable Ready",
  "Phoenix",
  "LiveView",
  "Absinthe",
  "Ecto",
  "Nerves",
  "Broadway",
  "Elixir",
  "Erlang",
  "OTP",
  "BEAM",
  "Mnesia",
  "Riak",
  "CouchDB",
  "Riak",
  "Couchbase",
  "DynamoDB",
  "DocumentDB",
  "Cosmos DB",
  "FaunaDB",
  "Neo4j",
  "ArangoDB",
  "OrientDB",
  "JanusGraph",
  "Dgraph",
  "TigerGraph",
  "TimescaleDB",
  "InfluxDB",
  "Prometheus",
  "VictoriaMetrics",
  "Thanos",
  "Loki",
  "Grafana",
  "Kibana",
  "Elastic",
  "OpenSearch",
  "MeiliSearch",
  "Algolia",
  "Typesense",
  "Zinc",
  "Qdrant",
  "Milvus",
  "Weaviate",
  "Pinecone",
  "Chroma",
  "Faiss",
  "Annoy",
  "Hnswlib",
  "NMSLIB",
  "Jina",
  "Haystack",
  "LangChain",
  "LlamaIndex",
  "AutoGPT",
  "BabyAGI",
  "GPT-4",
  "Claude",
  "PaLM",
  "LLaMA",
  "Falcon",
  "Mistral",
  "Mixtral",
  "Stable Diffusion",
  "DALL-E",
  "Midjourney",
  "SDXL",
  "ControlNet",
  "LoRA",
  "DreamBooth",
  "Textual Inversion",
  "Hypernetworks",
  "AUTOMATIC1111",
  "ComfyUI",
  "InvokeAI",
  "Fooocus",
  "SD.Next",
  "Kohya",
  "TensorRT",
  "ONNX",
  "OpenVINO",
  "Core ML",
  "ML Kit",
  "MediaPipe",
  "TensorFlow Lite",
  "PyTorch Mobile",
  "TFLite",
  "ONNX Runtime",
  "TVM",
  "IREE",
  "XLA",
  "JAX",
  "Flax",
  "Haiku",
  "Trax",
  "Sonnet",
  "Optax",
  "Chex",
  "RLax",
  "Acme",
  "Dopamine",
  "Ray",
  "RLLib",
  "Stable Baselines",
  "CleanRL",
  "Tianshou",
  "PettingZoo",
  "Gymnasium",
  "Procgen",
  "MinAtar",
  "ALE",
  "Retro",
  "VizDoom",
  "DeepMind Lab",
  "Unity ML-Agents",
  "Godot RL",
  "Mujoco",
  "PyBullet",
  "DART",
  "ODE",
  "Box2D",
  "Chipmunk",
  "Matter.js",
  "P2.js",
  "Planck.js",
  "Cannon.js",
  "Ammo.js",
  "PhysX",
  "Havok",
  "Bullet",
  "ODE",
  "Newton",
  "Tokamak",
  "Jolt",
  "React Physics",
  "Rapier",
  "XPhysics",
  "Physijs",
  "Oimo.js",
  "p2.js",
  "planck.js",
  "cannon.js",
  "ammo.js",
  "physx.js",
  "havok.js",
  "bullet.js",
  "ode.js",
  "newton.js",
  "tokamak.js",
  "jolt.js",
  "react-physics.js",
  "rapier.js",
  "xphysics.js",
  "physijs.js",
  "oimo.js",
  "p2.js",
  "planck.js",
  "cannon.js",
  "ammo.js",
  "physx.js",
  "havok.js",
  "bullet.js",
  "ode.js",
  "newton.js",
  "tokamak.js",
  "jolt.js",
  "react-physics.js",
  "rapier.js",
  "xphysics.js",
  "physijs.js",
  "oimo.js",
]

[params.writingsGrid]
columns = 3     # Number of columns in the grid (can be 3, 4, 5, etc.)
postsToShow = 6 # Number of posts to display in the grid

[params.forms.newsletter]
action = "https://app.kit.com/forms/7961988/subscriptions"
formId = "7961988"
uid = "842da55da6"
format = "inline"
version = "5"
