baseURL = 'https://nexo.sh/'
languageCode = 'en-us'
title = 'nexo blog'
theme = "cactus"
copyright = "Oleg Pustovit"

[params]
rss = true
description = "I’m a Lead Software Engineer at an early-stage startup, focused on building scalable infrastructure with Kubernetes, Go, and GraphQL. I have a strong background in system design, GPU programming, and computer graphics, and have led multiple startups from 0 to 1 through MVP development. This site is a collection of my technical write-ups, startup lessons, and occasional experiments in software engineering."
metaDescription = "Technical blog by Oleg Pustovit, covering scalable infrastructure, MVPs, Kubernetes, Go, GraphQL, and startup engineering lessons."
metaKeywords = "Software Engineering, Kubernetes, Go, GraphQL, Startups, MVP, System Design, Tech Blog, Oleg Pustovit"
colortheme = "classic"
worksFor = "Early-stage startup"
jobTitle = "Lead Software Engineer"
author = "Oleg Pustovit"


[[params.social]]
name = "github"
link = "https://github.com/nexo-tech"

[[params.social]]
name = "email"
link = "oleg@nexo.sh"

[[params.social]]
name = "x-twitter"
link = "https://x.com/nexo_v1"

[[params.social]]
name = "behance"
link = "https://www.behance.net/crystalboxes"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 3

[[menu.main]]
name = "Privacy"
url = "/privacy-policy"
weight = 4

