[skills]
primary = [
  "React",
  "Node.js",
  "TypeScript",
  "AWS",
  "Python",
  "Go",
  "Kubernetes",
  "Docker",
  "PostgreSQL",
  "Redis",
  "GraphQL",
  "Next.js",
  "Rust",
  "Swift",
  "Nest.js",
  "FastAPI",
]
secondary = [
  "MongoDB",
  "MySQL",
  "Elasticsearch",
  "RabbitMQ",
  "Kafka",
  "WebSocket",
  "gRPC",
  "OpenCV",
  "Pandas",
  "NumPy",
  "Django",
  "Flask",
  "FastAPI",
  "Gin",
  "Echo",
  "Actix",
  "Vue.js",
  "Angular",
  "Svelte",
  "Remix",
  "Nuxt",
  "Tailwind CSS",
  "Styled Components",
  "Sass",
  "Less",
  "PostCSS",
  "Bootstrap",
  "Material UI",
  "Ant Design",
  "Framer Motion",
  "Three.js",
  "D3.js",
  "Jest",
  "Cypress",
  "Playwright",
  "Vitest",
  "Mocha",
  "Chai",
  "Terraform",
  "Ansible",
  "Prometheus",
  "Grafana",
  "ELK Stack",
  "GitHub Actions",
  "GitLab CI",
  "Jenkins",
  "ArgoCD",
  "Flux",
  "Helm",
  "Nginx",
  "Apache",
  "Caddy",
  "Prisma",
  "TypeORM",
  "Sequelize",
  "Mongoose",
  "SQLAlchemy",
  "Storybook",
  "Sentry",
  "Datadog",
  "Stripe",
  "PayPal",
  "Twilio",
  "SendGrid",
  "Mailchimp",
  "Firebase",
  "Supabase",
  "Hasura",
  "WebRTC",
  "WebGL",
  "WebAssembly",
  "WebSocket",
  "PWA",
  "Service Workers",
  "IndexedDB",
  "Web Storage",
  "Web Crypto",
  "Web Components",
  "Shadow DOM",
  "Custom Elements",
  "HTML Templates",
  "CSS Grid",
  "CSS Flexbox",
  "CSS Variables",
  "CSS Animations",
  "CSS Transitions",
  "Webpack",
  "Vite",
  "Rollup",
  "Parcel",
  "ESBuild",
  "SWC",
  "Babel",
  "ESLint",
  "Prettier",
  "Husky",
  "Jira",
  "Trello",
  "Asana",
  "ClickUp",
  "Notion",
  "Confluence",
  "Figma",
  "Sketch",
  "Adobe XD",
  "VS Code",
  "IntelliJ",
  "WebStorm",
  "Sublime Text",
  "Vim",
  "Neovim",
  "Git",
  "Mercurial",
  "Linux",
  "macOS",
  "Windows",
  "HTTP/2",
  "HTTP/3",
  "gRPC",
  "GraphQL",
  "REST",
  "OAuth",
  "JWT",
  "AES",
  "RSA",
  "SHA",
  "HMAC",
  "TLS",
  "SSL",
  "OpenVPN",
  "SSH",
  "DNS",
  "SMTP",
  "CDN",
  "Edge Computing",
  "Serverless",
  "Microservices",
  "Monolith",
  "DDD",
  "TDD",
  "BDD",
  "Clean Architecture",
  "SOLID",
  "DRY",
  "KISS",
  "YAGNI",
  "GRASP",
  "Design Patterns",
  "Agile",
  "Scrum",
  "Kanban",
  "XP",
  "Lean",
  "SAFe",
  "DevOps",
  "CI/CD",
  "GitOps",
  "Infrastructure as Code",
  "Configuration as Code",
  "Observability",
  "Telemetry",
  "Tracing",
  "Logging",
  "Monitoring",
  "Performance",
  "Security",
  "Privacy",
  "Compliance",
  "GDPR",
  "CCPA",
  "HIPAA",
  "SOC 2",
  "ISO 27001",
  "PCI DSS",
]

tertiary = [
  "Turbo",
  "DynamoDB",
  "DocumentDB",
  "Neo4j",
  "ArangoDB",
  "Prometheus",
  "Loki",
  "Grafana",
  "Kibana",
  "Elastic",
  "OpenSearch",
  "Algolia",
  "Pinecone",
  "LangChain",
  "LlamaIndex",
  "AutoGPT",
  "GPT-4",
  "Claude",
  "PaLM",
  "LLaMA",
  "Stable Diffusion",
  "DALL-E",
  "Midjourney",
  "SDXL",
  "LoRA",
  "Sonnet",
  "Box2D",
  "P2.js",
  "Ammo.js",
  "PhysX",
  "Havok",
  "Bullet",
  "ODE",
  "Newton",
  "Tokamak",
  "Jolt",
  "React Physics",
  "p2.js",
  "ammo.js",
  "physx.js",
  "havok.js",
  "bullet.js",
  "react-physics.js",
  "cannon.js",
  "Express.js",
  "Koa",
  "Hono",
  "Remix",
  "Astro",
  "SvelteKit",
  "Nuxt",
  "Gatsby",
  "Apollo",
  "URQL",
  "Relay",
  "tRPC",
  "Zod",
  "TypeORM",
  "Sequelize",
  "MikroORM",
  "Drizzle",
  "Kysely",
  "Pydantic",
  "SQLAlchemy",
  "TortoiseORM",
  "Django ORM",
  "Mongoose",
  "Redis OM",
  "ioredis",
  "Bull",
  "Agenda",
  "BullMQ",
  "Celery",
  "RQ",
  "Huey",
  "Dramatiq",
  "FastStream",
  "KafkaJS",
  "kafkajs",
  "Pulsar",
  "NATS",
]
