
[skills]
primary = [
  "React",
  "Node.js",
  "TypeScript",
  "AWS",
  "Python",
  "Go",
  "Kubernetes",
  "Docker",
  "PostgreSQL",
  "Redis",
  "GraphQL",
  "Next.js",
  "Rust",
  "Swift",
  "Java",       # no
  "Kotlin",     # no
]
secondary = [
  "MongoDB",
  "MySQL",
  "Elasticsearch",
  "RabbitMQ",
  "Kafka",
  "WebSocket",
  "gRPC",
  "OpenCV",
  "Pandas",
  "NumPy",
  "Django",
  "Flask",
  "FastAPI",
  "Gin",
  "Echo",
  "Actix",
  "Vue.js",
  "Angular",
  "Svelte",
  "Remix",
  "Nuxt",
  "Tailwind CSS",
  "Styled Components",
  "Sass",
  "Less",
  "PostCSS",
  "Bootstrap",
  "Material UI",
  "Ant Design",
  "Framer Motion",
  "Three.js",
  "D3.js",
  "Jest",
  "Cypress",
  "Playwright",
  "Vitest",
  "Mocha",
  "Chai",
  "Terraform",
  "Ansible",
  "Prometheus",
  "Grafana",
  "ELK Stack",
  "GitHub Actions",
  "GitLab CI",
  "Jenkins",
  "ArgoCD",
  "Flux",
  "Helm",
  "Nginx",
  "Apache",
  "Caddy",
  "Prisma",
  "TypeORM",
  "Sequelize",
  "Mongoose",
  "SQLAlchemy",
  "Storybook",
  "Sentry",
  "Datadog",
  "Stripe",
  "PayPal",
  "Twilio",
  "SendGrid",
  "Mailchimp",
  "Firebase",
  "Supabase",
  "Hasura",
  "WebRTC",
  "WebGL",
  "WebAssembly",
  "WebSocket",
  "PWA",
  "Service Workers",
  "IndexedDB",
  "Web Storage",
  "Web Crypto",
  "Web Components",
  "Shadow DOM",
  "Custom Elements",
  "HTML Templates",
  "CSS Grid",
  "CSS Flexbox",
  "CSS Variables",
  "CSS Animations",
  "CSS Transitions",
  "Webpack",
  "Vite",
  "Rollup",
  "Parcel",
  "ESBuild",
  "SWC",
  "Babel",
  "ESLint",
  "Prettier",
  "Husky",
  "Jira",
  "Trello",
  "Asana",
  "ClickUp",
  "Notion",
  "Confluence",
  "Figma",
  "Sketch",
  "Adobe XD",
  "VS Code",
  "IntelliJ",
  "WebStorm",
  "Sublime Text",
  "Vim",
  "Neovim",
  "Git",
  "Mercurial",
  "Linux",
  "macOS",
  "Windows",
  "HTTP/2",
  "HTTP/3",
  "gRPC",
  "GraphQL",
  "REST",
  "OAuth",
  "JWT",
  "AES",
  "RSA",
  "SHA",
  "HMAC",
  "TLS",
  "SSL",
  "OpenVPN",
  "SSH",
  "DNS",
  "SMTP",
  "CDN",
  "Edge Computing",
  "Serverless",
  "Microservices",
  "Monolith",
  "DDD",
  "TDD",
  "BDD",
  "Clean Architecture",
  "SOLID",
  "DRY",
  "KISS",
  "YAGNI",
  "Design Patterns",
  "Agile",
  "Scrum",
  "Kanban",
  "Lean",
  "DevOps",
  "CI/CD",
  "GitOps",
  "Infrastructure as Code",
  "Configuration as Code",
  "Observability",
  "Telemetry",
  "Tracing",
  "Logging",
  "Monitoring",
  "Performance",
  "Security",
  "Accessibility",
  "SEO",
  "Analytics",
  "Machine Learning",
  "Computer Vision",
  "Cryptography",
  "IoT",
  "AR",
  "VR",
  "MR",
  "XR",
  "WebXR",
  "Unity",
  "Unreal Engine",
  "Mobile Development",
  "Desktop Development",
  "Cloud Computing",
  "Edge Computing",
  "Distributed Systems",
  "High Availability",
  "Fault Tolerance",
  "Resilience",
  "Scalability",
  "Performance",
  "Security",
  "Privacy",
  "Cassandra",              # no
  "TensorFlow",             # no
  "PyTorch",                # no
  "Scikit-learn",           # no
  "Spring Boot",            # no
  "Rocket",                 # no
  "Solid",                  # no
  "Qwik",                   # no
  "Astro",                  # no
  "Chakra UI",              # no
  "Sinon",                  # no
  "JUnit",                  # no
  "Puppet",                 # no
  "Chef",                   # no
  "CircleCI",               # no
  "Istio",                  # no
  "Linkerd",                # no
  "Envoy",                  # no
  "Traefik",                # no
  "Hibernate",              # no
  "New Relic",              # no
  "LogRocket",              # no
  "Amplitude",              # no
  "Square",                 # no
  "Plaid",                  # no
  "Appwrite",               # no
  "Sanity",                 # no
  "Contentful",             # no
  "WebAuthn",               # no
  "WebTransport",           # no
  "Stylelint",              # no
  "lint-staged",            # no
  "Commitlint",             # no
  "Monday",                 # no
  "InVision",               # no
  "Zeplin",                 # no
  "Abstract",               # no
  "SVN",                    # no
  "Perforce",               # no
  "Plastic SCM",            # no
  "Fossil",                 # no
  "BSD",                    # no
  "Solaris",                # no
  "AIX",                    # no
  "HP-UX",                  # no
  "ARM",                    # no
  "x86",                    # no
  "RISC-V",                 # no
  "MIPS",                   # no
  "PowerPC",                # no
  "SPARC",                  # no
  "Itanium",                # no
  "TCP/IP",                 # no
  "QUIC",                   # no
  "OpenID",                 # no
  "SAML",                   # no
  "OIDC",                   # no
  "LDAP",                   # no
  "Kerberos",               # no
  "ECC",                    # no
  "PBKDF2",                 # no
  "Argon2",                 # no
  "IPSec",                  # no
  "WireGuard",              # no
  "SFTP",                   # no
  "DHCP",                   # no
  "NTP",                    # no
  "SNMP",                   # no
  "IMAP",                   # no
  "POP3",                   # no
  "Event Sourcing",         # no
  "CQRS",                   # no
  "GRASP",                  # no
  "XP",                     # no
  "SAFe",                   # no
  "Deep Learning",          # no
  "NLP",                    # no
  "Blockchain",             # no
  "Quantum Computing",      # no
  "Game Development",       # no
  "Fog Computing",          # no
  "Grid Computing",         # no
  "Compliance",             # no
  "GDPR",                   # no
  "CCPA",                   # no
  "HIPAA",                  # no
  "SOC 2",                  # no
  "ISO 27001",              # no
  "PCI DSS",                # no
]

tertiary = [

  "Turbo",
  "DynamoDB",
  "DocumentDB",
  "Neo4j",
  "ArangoDB",
  "Prometheus",
  "Loki",
  "Grafana",
  "Kibana",
  "Elastic",
  "OpenSearch",
  "Algolia",
  "Pinecone",
  "LangChain",
  "LlamaIndex",
  "AutoGPT",
  "GPT-4",
  "Claude",
  "PaLM",
  "LLaMA",
  "Stable Diffusion",
  "DALL-E",
  "Midjourney",
  "SDXL",
  "LoRA",
  "Sonnet",
  "Box2D",
  "P2.js",
  "Ammo.js",
  "PhysX",
  "Havok",
  "Bullet",
  "ODE",
  "Newton",
  "Tokamak",
  "Jolt",
  "React Physics",
  "p2.js",
  "ammo.js",
  "physx.js",
  "havok.js",
  "bullet.js",
  "react-physics.js",
  "cannon.js",
  "Alpine.js",         # no
  "Stimulus",          # no
  "Hotwire",           # no
  "Strada",            # no
  "Cable Ready",       # no
  "Phoenix",           # no
  "LiveView",          # no
  "Absinthe",          # no
  "Ecto",              # no
  "Nerves",            # no
  "Broadway",          # no
  "Elixir",            # no
  "Erlang",            # no
  "OTP",               # no
  "BEAM",              # no
  "Mnesia",            # no
  "Riak",              # no
  "CouchDB",           # no
  "Riak",              # no
  "Couchbase",         # no
  "Cosmos DB",         # no
  "FaunaDB",           # no
  "OrientDB",          # no
  "JanusGraph",        # no
  "Dgraph",            # no
  "TigerGraph",        # no
  "TimescaleDB",       # no
  "InfluxDB",          # no
  "VictoriaMetrics",   # no
  "Thanos",            # no
  "MeiliSearch",       # no
  "Typesense",         # no
  "Zinc",              # no
  "Qdrant",            # no
  "Milvus",            # no
  "Weaviate",          # no
  "Chroma",            # no
  "Faiss",             # no
  "Annoy",             # no
  "Hnswlib",           # no
  "NMSLIB",            # no
  "Jina",              # no
  "Haystack",          # no
  "BabyAGI",           # no
  "Falcon",            # no
  "Mistral",           # no
  "Mixtral",           # no
  "ControlNet",        # no
  "DreamBooth",        # no
  "Textual Inversion", # no
  "Hypernetworks",     # no
  "AUTOMATIC1111",     # no
  "ComfyUI",           # no
  "InvokeAI",          # no
  "Fooocus",           # no
  "SD.Next",           # no
  "Kohya",             # no
  "TensorRT",          # no
  "ONNX",              # no
  "OpenVINO",          # no
  "Core ML",           # no
  "ML Kit",            # no
  "MediaPipe",         # no
  "TensorFlow Lite",   # no
  "PyTorch Mobile",    # no
  "TFLite",            # no
  "ONNX Runtime",      # no
  "TVM",               # no
  "IREE",              # no
  "XLA",               # no
  "JAX",               # no
  "Flax",              # no
  "Haiku",             # no
  "Trax",              # no
  "Optax",             # no
  "Chex",              # no
  "RLax",              # no
  "Acme",              # no
  "Dopamine",          # no
  "Ray",               # no
  "RLLib",             # no
  "Stable Baselines",  # no
  "CleanRL",           # no
  "Tianshou",          # no
  "PettingZoo",        # no
  "Gymnasium",         # no
  "Procgen",           # no
  "MinAtar",           # no
  "ALE",               # no
  "Retro",             # no
  "VizDoom",           # no
  "DeepMind Lab",      # no
  "Unity ML-Agents",   # no
  "Godot RL",          # no
  "Mujoco",            # no
  "PyBullet",          # no
  "DART",              # no
  "ODE",               # no
  "Chipmunk",          # no
  "Matter.js",         # no
  "Planck.js",         # no
  "Rapier",            # no
  "XPhysics",          # no
  "Physijs",           # no
  "Oimo.js",           # no
  "planck.js",         # no
  "ode.js",            # no
  "newton.js",         # no
  "tokamak.js",        # no
  "jolt.js",           # no
  "rapier.js",         # no
  "xphysics.js",       # no
  "physijs.js",        # no
  "oimo.js",           # no
  "p2.js",             # no
  "planck.js",         # no
  "cannon.js",         # no
  "ammo.js",           # no
  "physx.js",          # no
  "havok.js",          # no
  "bullet.js",         # no
  "ode.js",            # no
  "newton.js",         # no
  "tokamak.js",        # no
  "jolt.js",           # no
  "react-physics.js",  # no
  "rapier.js",         # no
  "xphysics.js",       # no
  "physijs.js",        # no
  "oimo.js",           # no
]
